AWSTemplateFormatVersion: "2010-09-09"
Description: aaa
Resources:
  DatabaseServer:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: testDefault
      DBInstanceClass: db.t2.micro
      MasterUsername: master
      MasterUserPassword: somesecret
      Engine: postgres
      AllocatedStorage: 20
      PubliclyAccessible: false